baseURL = "https://stupefied-hawking-fb6338.netlify.com/"
languageCode = "en-us"
title = "My New Hugo Site"


theme = [
  "theme",
  "github.com/pointyfar/hugo-debug-drawer"
  ]

[module]

  [[module.imports]]
    path = "github.com/pointyfar/hmd-content"
    disable = false

    [[module.imports.mounts]]
    source = "content/looking-glass"
    target = "content/looking-glass"

    [[module.imports.mounts]]
    source = "animals"
    target = "content/animals"

    [[module.imports.mounts]]
    source = "plants"
    target = "content/animals"

    [[module.imports]]
      path = "github.com/jgthms/bulma"
      disable = false
      [[module.imports.mounts]]
        source = "."
        target = "assets/bulma"