theme = [
  "github.com/pointyfar/hugo-debug-drawer", 
  "github.com/yihui/hugo-xmin"
  ]

layoutDir = "layouts-xmin"
publishDir = "public/__xmin"

[module]

  [[module.imports]]
  path = "github.com/pointyfar/hmd-content"
  disable = false

    [[module.imports.mounts]]
    source = "content/looking-glass"
    target = "content/looking-glass"

    [[module.imports.mounts]]
    source = "animals"
    target = "content/animals"

    [[module.imports.mounts]]
    source = "plants"
    target = "content/animals"

